# Generated by Django 3.2.7 on 2021-10-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Subject', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=40)),
                ('message', models.TextField()),
            ],
        ),
    ]
